/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mobilephone2.implementation;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Manuel Izquierdo
 * @author Francisco Llamas
 */
public class Phone extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
    private Locale currentLocale;
    
    public Phone() {
        //setUndecorated(true);
        //Obtener Locale por defecto
        //currentLocale = new Locale("fr", "FR");

        //Obtener idioma y país de Locale
        //currentLocale.getLanguage();
        //currentLocale.getCountry();

        //ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
        
        initComponents();
        //setBackground(new Color(0,0,0,0));
        //body.setBackground(Color.WHITE);
        time.setText(sdf.format(new Date()));
        
        movil.setVisible(true);
            pantalla_movil.setVisible(true);
                barra_notificaciones.setVisible(true);
                    aplicacion.setVisible(true);
                        inicio_sesion.setVisible(true);
                        interfaz_alumno.setVisible(false);
                            MenuAlumno.setVisible(false);
                            Header.setVisible(false);
                            seleccion.setVisible(false);
                            consultar_notas.setVisible(false);
                            consultar_matricula.setVisible(false);
                            consultar_abonare.setVisible(false);
                            consultar_grupo_grande.setVisible(false);
                            consultar_grupo_practica.setVisible(false);
                            consultar_horario.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Movil_imagen = new javax.swing.JLabel();
        movil = new javax.swing.JPanel();
        espacio_vacio_superior = new javax.swing.JLabel();
        espacio_vacio_inferior = new javax.swing.JLabel();
        espacio_vacio_izquierda = new javax.swing.JLabel();
        espacio_vacio_derecha = new javax.swing.JLabel();
        pantalla_movil = new javax.swing.JPanel();
        barra_notificaciones = new javax.swing.JPanel();
        senal = new javax.swing.JLabel();
        bateria = new javax.swing.JLabel();
        wifi = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        aplicacion = new javax.swing.JPanel();
        inicio_sesion = new javax.swing.JPanel();
        Logo_UCO = new javax.swing.JLabel();
        Usuario_campo = new javax.swing.JTextField();
        Usuario_etiqueta = new javax.swing.JLabel();
        Contraseña_etiqueta = new javax.swing.JLabel();
        Contraseña_campo = new javax.swing.JPasswordField();
        Mostrar_contraseña = new javax.swing.JCheckBox();
        Password_olvidada = new javax.swing.JLabel();
        inicio_de_sesion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        Selecione_idioma1 = new javax.swing.JLabel();
        espanol_boton = new javax.swing.JButton();
        ingles_boton = new javax.swing.JButton();
        frances_boton = new javax.swing.JButton();
        interfaz_alumno = new javax.swing.JPanel();
        MenuAlumno = new javax.swing.JPanel();
        MenuBotonCerrar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Inicio_Imagen = new javax.swing.JLabel();
        Moodle = new javax.swing.JLabel();
        Moodle_imagen = new javax.swing.JLabel();
        Acerca_de = new javax.swing.JLabel();
        Acerca_de_imagen = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        MenuBoton = new javax.swing.JLabel();
        UCOApp = new javax.swing.JLabel();
        seleccion = new javax.swing.JPanel();
        Logo_UCO1 = new javax.swing.JLabel();
        consultar_notas_boton = new javax.swing.JButton();
        consultar_matricula_boton = new javax.swing.JButton();
        consultar_horario_boton = new javax.swing.JButton();
        informacion_grado_boton1 = new javax.swing.JButton();
        consultar_notas = new javax.swing.JPanel();
        Grado_Ingenieria = new javax.swing.JLabel();
        barra_creditos = new javax.swing.JProgressBar();
        creditos_etiqueta = new javax.swing.JLabel();
        escuela = new javax.swing.JLabel();
        primera_asignatura = new javax.swing.JPanel();
        titulo_primera = new javax.swing.JLabel();
        convocatoria_primero = new javax.swing.JLabel();
        aprobado_texto_primera = new javax.swing.JLabel();
        aprobado_fondo_primera = new javax.swing.JLabel();
        aprobado_nota_primera = new javax.swing.JLabel();
        aprobado_fondo_nota_primera = new javax.swing.JLabel();
        segunda_asignatura = new javax.swing.JPanel();
        titulo_segunda = new javax.swing.JLabel();
        convocatoria_segunda = new javax.swing.JLabel();
        aprobado_texto_segunda = new javax.swing.JLabel();
        aprobado_fondo_segunda = new javax.swing.JLabel();
        aprobado_nota_segunda = new javax.swing.JLabel();
        aprobado_fondo_nota_segunda = new javax.swing.JLabel();
        consultar_matricula = new javax.swing.JPanel();
        consultar_abonare_boton = new javax.swing.JButton();
        consultar_grupo_grande_boton = new javax.swing.JButton();
        consultar_grupo_practicas_boton = new javax.swing.JButton();
        consultar_abonare = new javax.swing.JPanel();
        PDF = new javax.swing.JLabel();
        consultar_grupo_grande = new javax.swing.JPanel();
        primer_grupo = new javax.swing.JPanel();
        titulo_primer = new javax.swing.JLabel();
        grupo_texto_primer = new javax.swing.JLabel();
        fondo_primer = new javax.swing.JLabel();
        grupo_primer = new javax.swing.JLabel();
        grupo_fondo_primer = new javax.swing.JLabel();
        segundo_grupo = new javax.swing.JPanel();
        titulo_segundo = new javax.swing.JLabel();
        grupo_texto_segundo = new javax.swing.JLabel();
        fondo_segundo = new javax.swing.JLabel();
        grupo_segundo = new javax.swing.JLabel();
        grupo_fondo_segundo = new javax.swing.JLabel();
        consultar_grupo_practica = new javax.swing.JPanel();
        primer_grupo_practica = new javax.swing.JPanel();
        titulo_primer_grupo = new javax.swing.JLabel();
        texto_primer_grupo = new javax.swing.JLabel();
        fondo_primer_grupo = new javax.swing.JLabel();
        texto_primer_grupo_mediano = new javax.swing.JLabel();
        grupo_fondo_primer1 = new javax.swing.JLabel();
        segundo_grupo_practica = new javax.swing.JPanel();
        titulo_segundo_grupo = new javax.swing.JLabel();
        texto_segundo_grupo = new javax.swing.JLabel();
        fondo_segundo_grupo = new javax.swing.JLabel();
        texto_segundo_grupo_mediano = new javax.swing.JLabel();
        grupo_fondo_segundo1 = new javax.swing.JLabel();
        consultar_horario = new javax.swing.JPanel();
        horario = new javax.swing.JLabel();
        informacion_grado = new javax.swing.JPanel();
        primera_asignatura_matricula = new javax.swing.JPanel();
        titulo_primera_asignatura = new javax.swing.JLabel();
        texto_primera_asignatura = new javax.swing.JLabel();
        fondo_primer1 = new javax.swing.JLabel();
        curso_primera_asignatura = new javax.swing.JLabel();
        segunda_asignatura_matricula = new javax.swing.JPanel();
        titulo_segunda_asignatura = new javax.swing.JLabel();
        texto_segunda_asignatura = new javax.swing.JLabel();
        fondo_segunda_asignatura = new javax.swing.JLabel();
        curso_primera_asignatura1 = new javax.swing.JLabel();
        Logo_UCO2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("UCO App"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Movil_imagen.setBackground(new java.awt.Color(255, 255, 255));
        Movil_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cellphone.png"))); // NOI18N
        Movil_imagen.setName("Movil_imagen"); // NOI18N
        getContentPane().add(Movil_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 910));

        movil.setName("movil"); // NOI18N
        movil.setLayout(new java.awt.BorderLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mobilephone2/bundle/Bundle"); // NOI18N
        espacio_vacio_superior.setText(bundle.getString("Phone.espacio_vacio_superior.text")); // NOI18N
        espacio_vacio_superior.setAlignmentY(0.0F);
        espacio_vacio_superior.setName("espacio_vacio_superior"); // NOI18N
        espacio_vacio_superior.setPreferredSize(new java.awt.Dimension(49, 32));
        movil.add(espacio_vacio_superior, java.awt.BorderLayout.NORTH);

        espacio_vacio_inferior.setText(bundle.getString("Phone.espacio_vacio_inferior.text")); // NOI18N
        espacio_vacio_inferior.setAlignmentY(0.0F);
        espacio_vacio_inferior.setName("espacio_vacio_inferior"); // NOI18N
        espacio_vacio_inferior.setPreferredSize(new java.awt.Dimension(49, 32));
        movil.add(espacio_vacio_inferior, java.awt.BorderLayout.SOUTH);

        espacio_vacio_izquierda.setText(bundle.getString("Phone.espacio_vacio_izquierda.text")); // NOI18N
        espacio_vacio_izquierda.setAlignmentY(0.0F);
        espacio_vacio_izquierda.setName("espacio_vacio_izquierda"); // NOI18N
        espacio_vacio_izquierda.setPreferredSize(new java.awt.Dimension(28, 32));
        movil.add(espacio_vacio_izquierda, java.awt.BorderLayout.WEST);

        espacio_vacio_derecha.setText(bundle.getString("Phone.espacio_vacio_derecha.text")); // NOI18N
        espacio_vacio_derecha.setAlignmentY(0.0F);
        espacio_vacio_derecha.setName("espacio_vacio_derecha"); // NOI18N
        espacio_vacio_derecha.setPreferredSize(new java.awt.Dimension(28, 32));
        movil.add(espacio_vacio_derecha, java.awt.BorderLayout.EAST);

        pantalla_movil.setName("pantalla_movil"); // NOI18N
        pantalla_movil.setLayout(new java.awt.BorderLayout());

        barra_notificaciones.setBackground(new java.awt.Color(255, 255, 255));
        barra_notificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barra_notificaciones.setName("barra_notificaciones"); // NOI18N
        barra_notificaciones.setPreferredSize(new java.awt.Dimension(387, 32));

        senal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signal-icon (1).jpg"))); // NOI18N
        senal.setName("senal"); // NOI18N

        bateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/battery-icon (1).jpg"))); // NOI18N
        bateria.setName("bateria"); // NOI18N

        wifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wireless-icon.svg (1).png"))); // NOI18N
        wifi.setName("wifi"); // NOI18N

        time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        time.setName("time"); // NOI18N

        javax.swing.GroupLayout barra_notificacionesLayout = new javax.swing.GroupLayout(barra_notificaciones);
        barra_notificaciones.setLayout(barra_notificacionesLayout);
        barra_notificacionesLayout.setHorizontalGroup(
            barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_notificacionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(senal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wifi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barra_notificacionesLayout.setVerticalGroup(
            barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(barra_notificacionesLayout.createSequentialGroup()
                .addGroup(barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(senal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(wifi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pantalla_movil.add(barra_notificaciones, java.awt.BorderLayout.NORTH);

        aplicacion.setName("aplicacion"); // NOI18N
        aplicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio_sesion.setName("inicio_sesion"); // NOI18N

        Logo_UCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        Logo_UCO.setText(bundle.getString("Phone.Logo_UCO.text")); // NOI18N
        Logo_UCO.setName("Logo_UCO"); // NOI18N

        Usuario_campo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Usuario_campo.setText(bundle.getString("Phone.Usuario_campo.text")); // NOI18N
        Usuario_campo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        Usuario_campo.setName("Usuario_campo"); // NOI18N
        Usuario_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_campoActionPerformed(evt);
            }
        });

        Usuario_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Usuario_etiqueta.setText(bundle.getString("Phone.Usuario_etiqueta.text")); // NOI18N
        Usuario_etiqueta.setName("Usuario_etiqueta"); // NOI18N

        Contraseña_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Contraseña_etiqueta.setText(bundle.getString("Phone.Contraseña_etiqueta.text")); // NOI18N
        Contraseña_etiqueta.setName("Contraseña_etiqueta"); // NOI18N

        Contraseña_campo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Contraseña_campo.setText(bundle.getString("Phone.Contraseña_campo.text")); // NOI18N
        Contraseña_campo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        Contraseña_campo.setName("Contraseña_campo"); // NOI18N

        Mostrar_contraseña.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Mostrar_contraseña.setText(bundle.getString("Phone.Mostrar_contraseña.text")); // NOI18N
        Mostrar_contraseña.setName("Mostrar_contraseña"); // NOI18N
        Mostrar_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_contraseñaActionPerformed(evt);
            }
        });

        Password_olvidada.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        Password_olvidada.setText(bundle.getString("Phone.Password_olvidada.text")); // NOI18N
        Password_olvidada.setName("Password_olvidada"); // NOI18N

        inicio_de_sesion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        inicio_de_sesion.setText(bundle.getString("Phone.inicio_de_sesion.text")); // NOI18N
        inicio_de_sesion.setName("inicio_de_sesion"); // NOI18N
        inicio_de_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_de_sesionActionPerformed(evt);
            }
        });

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 125, 255)));
        jSeparator2.setName("jSeparator2"); // NOI18N

        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 125, 255)));
        jSeparator1.setName("jSeparator1"); // NOI18N

        Selecione_idioma1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Selecione_idioma1.setText(bundle.getString("Phone.Selecione_idioma1.text")); // NOI18N
        Selecione_idioma1.setName("Selecione_idioma1"); // NOI18N

        espanol_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera1_small.png"))); // NOI18N
        espanol_boton.setText(bundle.getString("Phone.espanol_boton.text")); // NOI18N
        espanol_boton.setName("espanol_boton"); // NOI18N
        espanol_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espanol_botonActionPerformed(evt);
            }
        });

        ingles_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera2.png"))); // NOI18N
        ingles_boton.setText(bundle.getString("Phone.ingles_boton.text")); // NOI18N
        ingles_boton.setName("ingles_boton"); // NOI18N
        ingles_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingles_botonActionPerformed(evt);
            }
        });

        frances_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera3.png"))); // NOI18N
        frances_boton.setText(bundle.getString("Phone.frances_boton.text")); // NOI18N
        frances_boton.setName("frances_boton"); // NOI18N
        frances_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frances_botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inicio_sesionLayout = new javax.swing.GroupLayout(inicio_sesion);
        inicio_sesion.setLayout(inicio_sesionLayout);
        inicio_sesionLayout.setHorizontalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_sesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_sesionLayout.createSequentialGroup()
                        .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Selecione_idioma1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Logo_UCO, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mostrar_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Password_olvidada)
                                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Usuario_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Usuario_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Contraseña_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Contraseña_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(103, 103, 103))))
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(espanol_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ingles_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(frances_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicio_sesionLayout.setVerticalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Logo_UCO)
                .addGap(27, 27, 27)
                .addComponent(Usuario_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Contraseña_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Password_olvidada, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mostrar_contraseña)
                .addGap(38, 38, 38)
                .addComponent(inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Selecione_idioma1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espanol_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingles_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frances_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        aplicacion.add(inicio_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 820));
        inicio_sesion.setBackground(Color.WHITE);

        interfaz_alumno.setBackground(new java.awt.Color(255, 255, 255));
        interfaz_alumno.setName("interfaz_alumno"); // NOI18N
        interfaz_alumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuAlumno.setBackground(new java.awt.Color(255, 255, 255));
        MenuAlumno.setForeground(new java.awt.Color(43, 43, 43));
        MenuAlumno.setName("MenuAlumno"); // NOI18N

        MenuBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_111152.png"))); // NOI18N
        MenuBotonCerrar.setName("MenuBotonCerrar"); // NOI18N
        MenuBotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBotonCerrarMouseClicked(evt);
            }
        });

        Nombre.setText(bundle.getString("Phone.Nombre.text")); // NOI18N
        Nombre.setName("Nombre"); // NOI18N

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar.png"))); // NOI18N
        Imagen.setName("Imagen"); // NOI18N

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        Logout.setName("Logout"); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        Inicio.setText(bundle.getString("Phone.Inicio.text")); // NOI18N
        Inicio.setName("Inicio"); // NOI18N
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });

        Inicio_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        Inicio_Imagen.setName("Inicio_Imagen"); // NOI18N
        Inicio_Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inicio_ImagenMouseClicked(evt);
            }
        });

        Moodle.setText(bundle.getString("Phone.Moodle.text")); // NOI18N
        Moodle.setName("Moodle"); // NOI18N

        Moodle_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moodle.png"))); // NOI18N
        Moodle_imagen.setName("Moodle_imagen"); // NOI18N

        Acerca_de.setText(bundle.getString("Phone.Acerca_de.text")); // NOI18N
        Acerca_de.setName("Acerca_de"); // NOI18N

        Acerca_de_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        Acerca_de_imagen.setName("Acerca_de_imagen"); // NOI18N

        javax.swing.GroupLayout MenuAlumnoLayout = new javax.swing.GroupLayout(MenuAlumno);
        MenuAlumno.setLayout(MenuAlumnoLayout);
        MenuAlumnoLayout.setHorizontalGroup(
            MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Moodle_imagen)
                            .addComponent(Inicio_Imagen)
                            .addComponent(Acerca_de_imagen))
                        .addGap(18, 18, 18)
                        .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Moodle)
                            .addComponent(Inicio)
                            .addComponent(Acerca_de)))
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Imagen)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuAlumnoLayout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logout))
                    .addComponent(MenuBotonCerrar))
                .addGap(45, 45, 45))
        );
        MenuAlumnoLayout.setVerticalGroup(
            MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuBotonCerrar)
                .addGap(18, 18, 18)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Acerca_de)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                                        .addComponent(Imagen)
                                        .addGap(32, 32, 32)
                                        .addComponent(Inicio_Imagen))
                                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                                        .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(Logout)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Inicio)))
                                .addGap(18, 18, 18)
                                .addComponent(Moodle_imagen))
                            .addComponent(Moodle))
                        .addGap(28, 28, 28)
                        .addComponent(Acerca_de_imagen)))
                .addContainerGap(567, Short.MAX_VALUE))
        );

        interfaz_alumno.add(MenuAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 850));

        Header.setBackground(new java.awt.Color(53, 53, 255));
        Header.setName("Header"); // NOI18N

        MenuBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-button.png"))); // NOI18N
        MenuBoton.setName("MenuBoton"); // NOI18N
        MenuBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBotonMouseClicked(evt);
            }
        });

        UCOApp.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        UCOApp.setText(bundle.getString("Phone.UCOApp.text")); // NOI18N
        UCOApp.setName("UCOApp"); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(MenuBoton)
                .addGap(18, 18, 18)
                .addComponent(UCOApp)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(MenuBoton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(UCOApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        interfaz_alumno.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        seleccion.setName("seleccion"); // NOI18N

        Logo_UCO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        Logo_UCO1.setText(bundle.getString("Phone.Logo_UCO1.text")); // NOI18N
        Logo_UCO1.setName("Logo_UCO1"); // NOI18N

        consultar_notas_boton.setBackground(new java.awt.Color(79, 79, 253));
        consultar_notas_boton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        consultar_notas_boton.setText(bundle.getString("Phone.consultar_notas_boton.text")); // NOI18N
        consultar_notas_boton.setName("consultar_notas_boton"); // NOI18N
        consultar_notas_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_notas_botonActionPerformed(evt);
            }
        });

        consultar_matricula_boton.setBackground(new java.awt.Color(53, 255, 53));
        consultar_matricula_boton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        consultar_matricula_boton.setText(bundle.getString("Phone.consultar_matricula_boton.text")); // NOI18N
        consultar_matricula_boton.setName("consultar_matricula_boton"); // NOI18N
        consultar_matricula_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_matricula_botonActionPerformed(evt);
            }
        });

        consultar_horario_boton.setBackground(new java.awt.Color(255, 0, 0));
        consultar_horario_boton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        consultar_horario_boton.setText(bundle.getString("Phone.consultar_horario_boton.text")); // NOI18N
        consultar_horario_boton.setName("consultar_horario_boton"); // NOI18N
        consultar_horario_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_horario_botonActionPerformed(evt);
            }
        });

        informacion_grado_boton1.setBackground(new java.awt.Color(201, 97, 248));
        informacion_grado_boton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        informacion_grado_boton1.setText(bundle.getString("Phone.informacion_grado_boton1.text")); // NOI18N
        informacion_grado_boton1.setName("informacion_grado_boton1"); // NOI18N
        informacion_grado_boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacion_grado_boton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccionLayout = new javax.swing.GroupLayout(seleccion);
        seleccion.setLayout(seleccionLayout);
        seleccionLayout.setHorizontalGroup(
            seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionLayout.createSequentialGroup()
                .addGroup(seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seleccionLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Logo_UCO1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seleccionLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultar_horario_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultar_notas_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultar_matricula_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(informacion_grado_boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        seleccionLayout.setVerticalGroup(
            seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Logo_UCO1)
                .addGap(187, 187, 187)
                .addGroup(seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar_notas_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar_matricula_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar_horario_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(informacion_grado_boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        interfaz_alumno.add(seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 410, 790));

        consultar_notas.setBackground(new java.awt.Color(255, 255, 255));
        consultar_notas.setName("consultar_notas"); // NOI18N
        consultar_notas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Grado_Ingenieria.setFont(new java.awt.Font("Ubuntu", 1, 23)); // NOI18N
        Grado_Ingenieria.setForeground(new java.awt.Color(0, 0, 0));
        Grado_Ingenieria.setText(bundle.getString("Phone.Grado_Ingenieria.text")); // NOI18N
        Grado_Ingenieria.setName("Grado_Ingenieria"); // NOI18N
        consultar_notas.add(Grado_Ingenieria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        barra_creditos.setMaximum(240);
        barra_creditos.setValue(60);
        barra_creditos.setName("barra_creditos"); // NOI18N
        consultar_notas.add(barra_creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 10));

        creditos_etiqueta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        creditos_etiqueta.setForeground(new java.awt.Color(0, 0, 0));
        creditos_etiqueta.setText(bundle.getString("Phone.creditos_etiqueta.text")); // NOI18N
        creditos_etiqueta.setName("creditos_etiqueta"); // NOI18N
        consultar_notas.add(creditos_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        escuela.setForeground(new java.awt.Color(0, 0, 0));
        escuela.setText(bundle.getString("Phone.escuela.text")); // NOI18N
        escuela.setName("escuela"); // NOI18N
        consultar_notas.add(escuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        primera_asignatura.setName("primera_asignatura"); // NOI18N
        primera_asignatura.setOpaque(false);
        primera_asignatura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_primera.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_primera.setForeground(new java.awt.Color(0, 0, 0));
        titulo_primera.setText(bundle.getString("Phone.titulo_primera.text")); // NOI18N
        titulo_primera.setName("titulo_primera"); // NOI18N
        primera_asignatura.add(titulo_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 12, -1, -1));

        convocatoria_primero.setForeground(new java.awt.Color(0, 0, 0));
        convocatoria_primero.setText(bundle.getString("Phone.convocatoria_primero.text")); // NOI18N
        convocatoria_primero.setName("convocatoria_primero"); // NOI18N
        primera_asignatura.add(convocatoria_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 39, -1, -1));

        aprobado_texto_primera.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_texto_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_texto_primera.setText(bundle.getString("Phone.aprobado_texto_primera.text")); // NOI18N
        aprobado_texto_primera.setName("aprobado_texto_primera"); // NOI18N
        primera_asignatura.add(aprobado_texto_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        aprobado_fondo_primera.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_primera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_primera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yellow_circle.png"))); // NOI18N
        aprobado_fondo_primera.setText(bundle.getString("Phone.aprobado_fondo_primera.text")); // NOI18N
        aprobado_fondo_primera.setName("aprobado_fondo_primera"); // NOI18N
        primera_asignatura.add(aprobado_fondo_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        aprobado_nota_primera.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_nota_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_nota_primera.setText(bundle.getString("Phone.aprobado_nota_primera.text")); // NOI18N
        aprobado_nota_primera.setName("aprobado_nota_primera"); // NOI18N
        primera_asignatura.add(aprobado_nota_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 40));

        aprobado_fondo_nota_primera.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_nota_primera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_nota_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_nota_primera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yellow_circle.png"))); // NOI18N
        aprobado_fondo_nota_primera.setText(bundle.getString("Phone.aprobado_fondo_nota_primera.text")); // NOI18N
        aprobado_fondo_nota_primera.setName("aprobado_fondo_nota_primera"); // NOI18N
        primera_asignatura.add(aprobado_fondo_nota_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_notas.add(primera_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 80));

        segunda_asignatura.setName("segunda_asignatura"); // NOI18N
        segunda_asignatura.setOpaque(false);
        segunda_asignatura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_segunda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_segunda.setForeground(new java.awt.Color(0, 0, 0));
        titulo_segunda.setText(bundle.getString("Phone.titulo_segunda.text")); // NOI18N
        titulo_segunda.setName("titulo_segunda"); // NOI18N
        segunda_asignatura.add(titulo_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 12, -1, -1));

        convocatoria_segunda.setForeground(new java.awt.Color(0, 0, 0));
        convocatoria_segunda.setText(bundle.getString("Phone.convocatoria_segunda.text")); // NOI18N
        convocatoria_segunda.setName("convocatoria_segunda"); // NOI18N
        segunda_asignatura.add(convocatoria_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 39, -1, -1));

        aprobado_texto_segunda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_texto_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_texto_segunda.setText(bundle.getString("Phone.aprobado_texto_segunda.text")); // NOI18N
        aprobado_texto_segunda.setName("aprobado_texto_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_texto_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        aprobado_fondo_segunda.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_segunda.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_segunda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_circle.png"))); // NOI18N
        aprobado_fondo_segunda.setText(bundle.getString("Phone.aprobado_fondo_segunda.text")); // NOI18N
        aprobado_fondo_segunda.setName("aprobado_fondo_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_fondo_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        aprobado_nota_segunda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_nota_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_nota_segunda.setText(bundle.getString("Phone.aprobado_nota_segunda.text")); // NOI18N
        aprobado_nota_segunda.setName("aprobado_nota_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_nota_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 40));

        aprobado_fondo_nota_segunda.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_nota_segunda.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_nota_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_nota_segunda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_circle.png"))); // NOI18N
        aprobado_fondo_nota_segunda.setText(bundle.getString("Phone.aprobado_fondo_nota_segunda.text")); // NOI18N
        aprobado_fondo_nota_segunda.setName("aprobado_fondo_nota_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_fondo_nota_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_notas.add(segunda_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 430, 80));

        interfaz_alumno.add(consultar_notas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        consultar_matricula.setBackground(new java.awt.Color(255, 255, 255));
        consultar_matricula.setName("consultar_matricula"); // NOI18N
        consultar_matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultar_abonare_boton.setText(bundle.getString("Phone.consultar_abonare_boton.text")); // NOI18N
        consultar_abonare_boton.setName("consultar_abonare_boton"); // NOI18N
        consultar_abonare_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_abonare_botonActionPerformed(evt);
            }
        });
        consultar_matricula.add(consultar_abonare_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 70));

        consultar_grupo_grande_boton.setText(bundle.getString("Phone.consultar_grupo_grande_boton.text")); // NOI18N
        consultar_grupo_grande_boton.setName("consultar_grupo_grande_boton"); // NOI18N
        consultar_grupo_grande_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_grupo_grande_botonActionPerformed(evt);
            }
        });
        consultar_matricula.add(consultar_grupo_grande_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 400, 70));

        consultar_grupo_practicas_boton.setText(bundle.getString("Phone.consultar_grupo_practicas_boton.text")); // NOI18N
        consultar_grupo_practicas_boton.setName("consultar_grupo_practicas_boton"); // NOI18N
        consultar_grupo_practicas_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_grupo_practicas_botonActionPerformed(evt);
            }
        });
        consultar_matricula.add(consultar_grupo_practicas_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 400, 70));

        interfaz_alumno.add(consultar_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        consultar_abonare.setBackground(new java.awt.Color(255, 255, 255));
        consultar_abonare.setName("consultar_abonare"); // NOI18N
        consultar_abonare.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PDF.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        PDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PDF.setText(bundle.getString("Phone.PDF.text")); // NOI18N
        PDF.setName("PDF"); // NOI18N
        PDF.setOpaque(true);
        consultar_abonare.add(PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 780));

        interfaz_alumno.add(consultar_abonare, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        consultar_grupo_grande.setBackground(new java.awt.Color(255, 255, 255));
        consultar_grupo_grande.setName("consultar_grupo_grande"); // NOI18N
        consultar_grupo_grande.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primer_grupo.setName("primer_grupo"); // NOI18N
        primer_grupo.setOpaque(false);
        primer_grupo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_primer.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_primer.setForeground(new java.awt.Color(0, 0, 0));
        titulo_primer.setText(bundle.getString("Phone.titulo_primer.text")); // NOI18N
        titulo_primer.setName("titulo_primer"); // NOI18N
        primer_grupo.add(titulo_primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        grupo_texto_primer.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        grupo_texto_primer.setForeground(new java.awt.Color(0, 0, 0));
        grupo_texto_primer.setText(bundle.getString("Phone.grupo_texto_primer.text")); // NOI18N
        grupo_texto_primer.setName("grupo_texto_primer"); // NOI18N
        primer_grupo.add(grupo_texto_primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        fondo_primer.setBackground(new java.awt.Color(255, 255, 0));
        fondo_primer.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        fondo_primer.setForeground(new java.awt.Color(0, 0, 0));
        fondo_primer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        fondo_primer.setText(bundle.getString("Phone.fondo_primer.text")); // NOI18N
        fondo_primer.setName("fondo_primer"); // NOI18N
        primer_grupo.add(fondo_primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        grupo_primer.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        grupo_primer.setForeground(new java.awt.Color(0, 0, 0));
        grupo_primer.setText(bundle.getString("Phone.grupo_primer.text")); // NOI18N
        grupo_primer.setName("grupo_primer"); // NOI18N
        primer_grupo.add(grupo_primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 40));

        grupo_fondo_primer.setBackground(new java.awt.Color(255, 255, 0));
        grupo_fondo_primer.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        grupo_fondo_primer.setForeground(new java.awt.Color(0, 0, 0));
        grupo_fondo_primer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        grupo_fondo_primer.setText(bundle.getString("Phone.grupo_fondo_primer.text")); // NOI18N
        grupo_fondo_primer.setName("grupo_fondo_primer"); // NOI18N
        primer_grupo.add(grupo_fondo_primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_grupo_grande.add(primer_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        segundo_grupo.setName("segundo_grupo"); // NOI18N
        segundo_grupo.setOpaque(false);
        segundo_grupo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_segundo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_segundo.setForeground(new java.awt.Color(0, 0, 0));
        titulo_segundo.setText(bundle.getString("Phone.titulo_segundo.text")); // NOI18N
        titulo_segundo.setName("titulo_segundo"); // NOI18N
        segundo_grupo.add(titulo_segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        grupo_texto_segundo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        grupo_texto_segundo.setForeground(new java.awt.Color(0, 0, 0));
        grupo_texto_segundo.setText(bundle.getString("Phone.grupo_texto_segundo.text")); // NOI18N
        grupo_texto_segundo.setName("grupo_texto_segundo"); // NOI18N
        segundo_grupo.add(grupo_texto_segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        fondo_segundo.setBackground(new java.awt.Color(255, 255, 0));
        fondo_segundo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        fondo_segundo.setForeground(new java.awt.Color(0, 0, 0));
        fondo_segundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        fondo_segundo.setText(bundle.getString("Phone.fondo_segundo.text")); // NOI18N
        fondo_segundo.setName("fondo_segundo"); // NOI18N
        segundo_grupo.add(fondo_segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        grupo_segundo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        grupo_segundo.setForeground(new java.awt.Color(0, 0, 0));
        grupo_segundo.setText(bundle.getString("Phone.grupo_segundo.text")); // NOI18N
        grupo_segundo.setName("grupo_segundo"); // NOI18N
        segundo_grupo.add(grupo_segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 40));

        grupo_fondo_segundo.setBackground(new java.awt.Color(255, 255, 0));
        grupo_fondo_segundo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        grupo_fondo_segundo.setForeground(new java.awt.Color(0, 0, 0));
        grupo_fondo_segundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        grupo_fondo_segundo.setText(bundle.getString("Phone.grupo_fondo_segundo.text")); // NOI18N
        grupo_fondo_segundo.setName("grupo_fondo_segundo"); // NOI18N
        segundo_grupo.add(grupo_fondo_segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_grupo_grande.add(segundo_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 60));

        interfaz_alumno.add(consultar_grupo_grande, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        consultar_grupo_practica.setBackground(new java.awt.Color(255, 255, 255));
        consultar_grupo_practica.setName("consultar_grupo_practica"); // NOI18N
        consultar_grupo_practica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primer_grupo_practica.setName("primer_grupo_practica"); // NOI18N
        primer_grupo_practica.setOpaque(false);
        primer_grupo_practica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_primer_grupo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_primer_grupo.setForeground(new java.awt.Color(0, 0, 0));
        titulo_primer_grupo.setText(bundle.getString("Phone.titulo_primer_grupo.text")); // NOI18N
        titulo_primer_grupo.setName("titulo_primer_grupo"); // NOI18N
        primer_grupo_practica.add(titulo_primer_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        texto_primer_grupo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        texto_primer_grupo.setForeground(new java.awt.Color(0, 0, 0));
        texto_primer_grupo.setText(bundle.getString("Phone.texto_primer_grupo.text")); // NOI18N
        texto_primer_grupo.setName("texto_primer_grupo"); // NOI18N
        primer_grupo_practica.add(texto_primer_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        fondo_primer_grupo.setBackground(new java.awt.Color(255, 255, 0));
        fondo_primer_grupo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        fondo_primer_grupo.setForeground(new java.awt.Color(0, 0, 0));
        fondo_primer_grupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        fondo_primer_grupo.setText(bundle.getString("Phone.fondo_primer_grupo.text")); // NOI18N
        fondo_primer_grupo.setName("fondo_primer_grupo"); // NOI18N
        primer_grupo_practica.add(fondo_primer_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        texto_primer_grupo_mediano.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        texto_primer_grupo_mediano.setForeground(new java.awt.Color(0, 0, 0));
        texto_primer_grupo_mediano.setText(bundle.getString("Phone.texto_primer_grupo_mediano.text")); // NOI18N
        texto_primer_grupo_mediano.setName("texto_primer_grupo_mediano"); // NOI18N
        primer_grupo_practica.add(texto_primer_grupo_mediano, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 40));

        grupo_fondo_primer1.setBackground(new java.awt.Color(255, 255, 0));
        grupo_fondo_primer1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        grupo_fondo_primer1.setForeground(new java.awt.Color(0, 0, 0));
        grupo_fondo_primer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        grupo_fondo_primer1.setText(bundle.getString("Phone.grupo_fondo_primer1.text")); // NOI18N
        grupo_fondo_primer1.setName("grupo_fondo_primer1"); // NOI18N
        primer_grupo_practica.add(grupo_fondo_primer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_grupo_practica.add(primer_grupo_practica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        segundo_grupo_practica.setName("segundo_grupo_practica"); // NOI18N
        segundo_grupo_practica.setOpaque(false);
        segundo_grupo_practica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_segundo_grupo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_segundo_grupo.setForeground(new java.awt.Color(0, 0, 0));
        titulo_segundo_grupo.setText(bundle.getString("Phone.titulo_segundo_grupo.text")); // NOI18N
        titulo_segundo_grupo.setName("titulo_segundo_grupo"); // NOI18N
        segundo_grupo_practica.add(titulo_segundo_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        texto_segundo_grupo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        texto_segundo_grupo.setForeground(new java.awt.Color(0, 0, 0));
        texto_segundo_grupo.setText(bundle.getString("Phone.texto_segundo_grupo.text")); // NOI18N
        texto_segundo_grupo.setName("texto_segundo_grupo"); // NOI18N
        segundo_grupo_practica.add(texto_segundo_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        fondo_segundo_grupo.setBackground(new java.awt.Color(255, 255, 0));
        fondo_segundo_grupo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        fondo_segundo_grupo.setForeground(new java.awt.Color(0, 0, 0));
        fondo_segundo_grupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        fondo_segundo_grupo.setText(bundle.getString("Phone.fondo_segundo_grupo.text")); // NOI18N
        fondo_segundo_grupo.setName("fondo_segundo_grupo"); // NOI18N
        segundo_grupo_practica.add(fondo_segundo_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        texto_segundo_grupo_mediano.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        texto_segundo_grupo_mediano.setForeground(new java.awt.Color(0, 0, 0));
        texto_segundo_grupo_mediano.setText(bundle.getString("Phone.texto_segundo_grupo_mediano.text")); // NOI18N
        texto_segundo_grupo_mediano.setName("texto_segundo_grupo_mediano"); // NOI18N
        segundo_grupo_practica.add(texto_segundo_grupo_mediano, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 40));

        grupo_fondo_segundo1.setBackground(new java.awt.Color(255, 255, 0));
        grupo_fondo_segundo1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        grupo_fondo_segundo1.setForeground(new java.awt.Color(0, 0, 0));
        grupo_fondo_segundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        grupo_fondo_segundo1.setText(bundle.getString("Phone.grupo_fondo_segundo1.text")); // NOI18N
        grupo_fondo_segundo1.setName("grupo_fondo_segundo1"); // NOI18N
        segundo_grupo_practica.add(grupo_fondo_segundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_grupo_practica.add(segundo_grupo_practica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 60));

        interfaz_alumno.add(consultar_grupo_practica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        consultar_horario.setBackground(new java.awt.Color(255, 255, 255));
        consultar_horario.setName("consultar_horario"); // NOI18N
        consultar_horario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horario.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        horario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        horario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horario.png"))); // NOI18N
        horario.setText(bundle.getString("Phone.horario.text")); // NOI18N
        horario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        horario.setName("horario"); // NOI18N
        consultar_horario.add(horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 780));

        interfaz_alumno.add(consultar_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        informacion_grado.setBackground(new java.awt.Color(255, 255, 255));
        informacion_grado.setName("informacion_grado"); // NOI18N
        informacion_grado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primera_asignatura_matricula.setName("primera_asignatura_matricula"); // NOI18N
        primera_asignatura_matricula.setOpaque(false);
        primera_asignatura_matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_primera_asignatura.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_primera_asignatura.setForeground(new java.awt.Color(0, 0, 0));
        titulo_primera_asignatura.setText(bundle.getString("Phone.titulo_primera_asignatura.text")); // NOI18N
        titulo_primera_asignatura.setName("titulo_primera_asignatura"); // NOI18N
        primera_asignatura_matricula.add(titulo_primera_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        texto_primera_asignatura.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        texto_primera_asignatura.setForeground(new java.awt.Color(0, 0, 0));
        texto_primera_asignatura.setText(bundle.getString("Phone.texto_primera_asignatura.text")); // NOI18N
        texto_primera_asignatura.setName("texto_primera_asignatura"); // NOI18N
        primera_asignatura_matricula.add(texto_primera_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        fondo_primer1.setBackground(new java.awt.Color(255, 255, 0));
        fondo_primer1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        fondo_primer1.setForeground(new java.awt.Color(0, 0, 0));
        fondo_primer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        fondo_primer1.setText(bundle.getString("Phone.fondo_primer1.text")); // NOI18N
        fondo_primer1.setName("fondo_primer1"); // NOI18N
        primera_asignatura_matricula.add(fondo_primer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 45));

        curso_primera_asignatura.setForeground(new java.awt.Color(0, 0, 0));
        curso_primera_asignatura.setText(bundle.getString("Phone.curso_primera_asignatura.text")); // NOI18N
        curso_primera_asignatura.setName("curso_primera_asignatura"); // NOI18N
        primera_asignatura_matricula.add(curso_primera_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        informacion_grado.add(primera_asignatura_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, 60));

        segunda_asignatura_matricula.setName("segunda_asignatura_matricula"); // NOI18N
        segunda_asignatura_matricula.setOpaque(false);
        segunda_asignatura_matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_segunda_asignatura.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_segunda_asignatura.setForeground(new java.awt.Color(0, 0, 0));
        titulo_segunda_asignatura.setText(bundle.getString("Phone.titulo_segunda_asignatura.text")); // NOI18N
        titulo_segunda_asignatura.setName("titulo_segunda_asignatura"); // NOI18N
        segunda_asignatura_matricula.add(titulo_segunda_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        texto_segunda_asignatura.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        texto_segunda_asignatura.setForeground(new java.awt.Color(0, 0, 0));
        texto_segunda_asignatura.setText(bundle.getString("Phone.texto_segunda_asignatura.text")); // NOI18N
        texto_segunda_asignatura.setName("texto_segunda_asignatura"); // NOI18N
        segunda_asignatura_matricula.add(texto_segunda_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        fondo_segunda_asignatura.setBackground(new java.awt.Color(255, 255, 0));
        fondo_segunda_asignatura.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        fondo_segunda_asignatura.setForeground(new java.awt.Color(0, 0, 0));
        fondo_segunda_asignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grey_circle.png"))); // NOI18N
        fondo_segunda_asignatura.setText(bundle.getString("Phone.fondo_segunda_asignatura.text")); // NOI18N
        fondo_segunda_asignatura.setName("fondo_segunda_asignatura"); // NOI18N
        segunda_asignatura_matricula.add(fondo_segunda_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 45));

        curso_primera_asignatura1.setForeground(new java.awt.Color(0, 0, 0));
        curso_primera_asignatura1.setText(bundle.getString("Phone.curso_primera_asignatura1.text")); // NOI18N
        curso_primera_asignatura1.setName("curso_primera_asignatura1"); // NOI18N
        segunda_asignatura_matricula.add(curso_primera_asignatura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        informacion_grado.add(segunda_asignatura_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, 60));

        Logo_UCO2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        Logo_UCO2.setText(bundle.getString("Phone.Logo_UCO2.text")); // NOI18N
        Logo_UCO2.setName("Logo_UCO2"); // NOI18N
        informacion_grado.add(Logo_UCO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 200, -1));

        interfaz_alumno.add(informacion_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        aplicacion.add(interfaz_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 820));
        interfaz_alumno.setBackground(Color.WHITE);

        pantalla_movil.add(aplicacion, java.awt.BorderLayout.CENTER);

        movil.add(pantalla_movil, java.awt.BorderLayout.CENTER);

        getContentPane().add(movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicio_de_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_de_sesionActionPerformed
        // TODO add your handling code here:
        inicio_sesion.setVisible(false);
        interfaz_alumno.setVisible(true);
            Header.setVisible(true);
            seleccion.setVisible(true);
    }//GEN-LAST:event_inicio_de_sesionActionPerformed

    private void Mostrar_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_contraseñaActionPerformed
        // TODO add your handling code here:
        if(Mostrar_contraseña.isSelected())
        Contraseña_campo.setEchoChar((char)0);
        else
        Contraseña_campo.setEchoChar('*');
    }//GEN-LAST:event_Mostrar_contraseñaActionPerformed

    private void Usuario_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_campoActionPerformed

    private void MenuBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBotonMouseClicked
        MenuAlumno.setVisible(true);
    }//GEN-LAST:event_MenuBotonMouseClicked

    private void MenuBotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBotonCerrarMouseClicked
        MenuAlumno.setVisible(false);
    }//GEN-LAST:event_MenuBotonCerrarMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        MenuAlumno.setVisible(false);
        interfaz_alumno.setVisible(false);
        inicio_sesion.setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void Inicio_ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inicio_ImagenMouseClicked
        seleccion.setVisible(true);
        MenuAlumno.setVisible(false);
        consultar_notas.setVisible(false);
        consultar_matricula.setVisible(false);
        consultar_abonare.setVisible(false);
        consultar_grupo_grande.setVisible(false);
        consultar_grupo_practica.setVisible(false);
        consultar_horario.setVisible(false);
    }//GEN-LAST:event_Inicio_ImagenMouseClicked

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        seleccion.setVisible(true);
        MenuAlumno.setVisible(false);
        consultar_notas.setVisible(false);
        consultar_matricula.setVisible(false);
        consultar_abonare.setVisible(false);
        consultar_grupo_grande.setVisible(false);
        consultar_grupo_practica.setVisible(false);
        consultar_horario.setVisible(false);
    }//GEN-LAST:event_InicioMouseClicked

    private void consultar_notas_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_notas_botonActionPerformed
        // TODO add your handling code here:
        seleccion.setVisible(false);
        consultar_notas.setVisible(true);
    }//GEN-LAST:event_consultar_notas_botonActionPerformed

    private void espanol_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espanol_botonActionPerformed
        // TODO add your handling code here:
        currentLocale = new Locale("es", "ES");
        
        ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
    }//GEN-LAST:event_espanol_botonActionPerformed

    private void ingles_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingles_botonActionPerformed
        // TODO add your handling code here:
        currentLocale = new Locale("en", "GB");
        
        ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
    }//GEN-LAST:event_ingles_botonActionPerformed

    private void frances_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frances_botonActionPerformed
        // TODO add your handling code here:
        currentLocale = new Locale("fr", "FR");

        ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
    }//GEN-LAST:event_frances_botonActionPerformed

    private void consultar_matricula_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_matricula_botonActionPerformed
        // TODO add your handling code here:
        seleccion.setVisible(false);
        consultar_matricula.setVisible(true);
    }//GEN-LAST:event_consultar_matricula_botonActionPerformed

    private void consultar_abonare_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_abonare_botonActionPerformed
        // TODO add your handling code here:
        consultar_matricula.setVisible(false);
        consultar_abonare.setVisible(true);
    }//GEN-LAST:event_consultar_abonare_botonActionPerformed

    private void consultar_grupo_grande_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_grupo_grande_botonActionPerformed
        // TODO add your handling code here:
        consultar_matricula.setVisible(false);
        consultar_grupo_grande.setVisible(true);
    }//GEN-LAST:event_consultar_grupo_grande_botonActionPerformed

    private void consultar_grupo_practicas_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_grupo_practicas_botonActionPerformed
        // TODO add your handling code here:
        consultar_matricula.setVisible(false);
        consultar_grupo_practica.setVisible(true);
    }//GEN-LAST:event_consultar_grupo_practicas_botonActionPerformed

    private void consultar_horario_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_horario_botonActionPerformed
        // TODO add your handling code here:
        seleccion.setVisible(false);
        consultar_horario.setVisible(true);
    }//GEN-LAST:event_consultar_horario_botonActionPerformed

    private void informacion_grado_boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacion_grado_boton1ActionPerformed
        // TODO add your handling code here:
        seleccion.setVisible(false);
        informacion_grado.setVisible(true);
    }//GEN-LAST:event_informacion_grado_boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acerca_de;
    private javax.swing.JLabel Acerca_de_imagen;
    private javax.swing.JPasswordField Contraseña_campo;
    private javax.swing.JLabel Contraseña_etiqueta;
    private javax.swing.JLabel Grado_Ingenieria;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Inicio_Imagen;
    private javax.swing.JLabel Logo_UCO;
    private javax.swing.JLabel Logo_UCO1;
    private javax.swing.JLabel Logo_UCO2;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel MenuAlumno;
    private javax.swing.JLabel MenuBoton;
    private javax.swing.JLabel MenuBotonCerrar;
    private javax.swing.JLabel Moodle;
    private javax.swing.JLabel Moodle_imagen;
    private javax.swing.JCheckBox Mostrar_contraseña;
    private javax.swing.JLabel Movil_imagen;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PDF;
    private javax.swing.JLabel Password_olvidada;
    private javax.swing.JLabel Selecione_idioma1;
    private javax.swing.JLabel UCOApp;
    private javax.swing.JTextField Usuario_campo;
    private javax.swing.JLabel Usuario_etiqueta;
    private javax.swing.JPanel aplicacion;
    private javax.swing.JLabel aprobado_fondo_nota_primera;
    private javax.swing.JLabel aprobado_fondo_nota_segunda;
    private javax.swing.JLabel aprobado_fondo_primera;
    private javax.swing.JLabel aprobado_fondo_segunda;
    private javax.swing.JLabel aprobado_nota_primera;
    private javax.swing.JLabel aprobado_nota_segunda;
    private javax.swing.JLabel aprobado_texto_primera;
    private javax.swing.JLabel aprobado_texto_segunda;
    private javax.swing.JProgressBar barra_creditos;
    private javax.swing.JPanel barra_notificaciones;
    private javax.swing.JLabel bateria;
    private javax.swing.JPanel consultar_abonare;
    private javax.swing.JButton consultar_abonare_boton;
    private javax.swing.JPanel consultar_grupo_grande;
    private javax.swing.JButton consultar_grupo_grande_boton;
    private javax.swing.JPanel consultar_grupo_practica;
    private javax.swing.JButton consultar_grupo_practicas_boton;
    private javax.swing.JPanel consultar_horario;
    private javax.swing.JButton consultar_horario_boton;
    private javax.swing.JPanel consultar_matricula;
    private javax.swing.JButton consultar_matricula_boton;
    private javax.swing.JPanel consultar_notas;
    private javax.swing.JButton consultar_notas_boton;
    private javax.swing.JLabel convocatoria_primero;
    private javax.swing.JLabel convocatoria_segunda;
    private javax.swing.JLabel creditos_etiqueta;
    private javax.swing.JLabel curso_primera_asignatura;
    private javax.swing.JLabel curso_primera_asignatura1;
    private javax.swing.JLabel escuela;
    private javax.swing.JLabel espacio_vacio_derecha;
    private javax.swing.JLabel espacio_vacio_inferior;
    private javax.swing.JLabel espacio_vacio_izquierda;
    private javax.swing.JLabel espacio_vacio_superior;
    private javax.swing.JButton espanol_boton;
    private javax.swing.JLabel fondo_primer;
    private javax.swing.JLabel fondo_primer1;
    private javax.swing.JLabel fondo_primer_grupo;
    private javax.swing.JLabel fondo_segunda_asignatura;
    private javax.swing.JLabel fondo_segundo;
    private javax.swing.JLabel fondo_segundo_grupo;
    private javax.swing.JButton frances_boton;
    private javax.swing.JLabel grupo_fondo_primer;
    private javax.swing.JLabel grupo_fondo_primer1;
    private javax.swing.JLabel grupo_fondo_segundo;
    private javax.swing.JLabel grupo_fondo_segundo1;
    private javax.swing.JLabel grupo_primer;
    private javax.swing.JLabel grupo_segundo;
    private javax.swing.JLabel grupo_texto_primer;
    private javax.swing.JLabel grupo_texto_segundo;
    private javax.swing.JLabel horario;
    private javax.swing.JPanel informacion_grado;
    private javax.swing.JButton informacion_grado_boton1;
    private javax.swing.JButton ingles_boton;
    private javax.swing.JButton inicio_de_sesion;
    private javax.swing.JPanel inicio_sesion;
    private javax.swing.JPanel interfaz_alumno;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel movil;
    private javax.swing.JPanel pantalla_movil;
    private javax.swing.JPanel primer_grupo;
    private javax.swing.JPanel primer_grupo_practica;
    private javax.swing.JPanel primera_asignatura;
    private javax.swing.JPanel primera_asignatura_matricula;
    private javax.swing.JPanel segunda_asignatura;
    private javax.swing.JPanel segunda_asignatura_matricula;
    private javax.swing.JPanel segundo_grupo;
    private javax.swing.JPanel segundo_grupo_practica;
    private javax.swing.JPanel seleccion;
    private javax.swing.JLabel senal;
    private javax.swing.JLabel texto_primer_grupo;
    private javax.swing.JLabel texto_primer_grupo_mediano;
    private javax.swing.JLabel texto_primera_asignatura;
    private javax.swing.JLabel texto_segunda_asignatura;
    private javax.swing.JLabel texto_segundo_grupo;
    private javax.swing.JLabel texto_segundo_grupo_mediano;
    private javax.swing.JLabel time;
    private javax.swing.JLabel titulo_primer;
    private javax.swing.JLabel titulo_primer_grupo;
    private javax.swing.JLabel titulo_primera;
    private javax.swing.JLabel titulo_primera_asignatura;
    private javax.swing.JLabel titulo_segunda;
    private javax.swing.JLabel titulo_segunda_asignatura;
    private javax.swing.JLabel titulo_segundo;
    private javax.swing.JLabel titulo_segundo_grupo;
    private javax.swing.JLabel wifi;
    // End of variables declaration//GEN-END:variables
}
