/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mobilephone2.implementation;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Manuel Izquierdo
 * @author Francisco Llamas
 */
public class Phone extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
    private Locale currentLocale;
    
    public Phone() {
        //setUndecorated(true);
        //Obtener Locale por defecto
        //currentLocale = new Locale("fr", "FR");

        //Obtener idioma y país de Locale
        //currentLocale.getLanguage();
        //currentLocale.getCountry();

        //ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
        
        initComponents();
        //setBackground(new Color(0,0,0,0));
        //body.setBackground(Color.WHITE);
        time.setText(sdf.format(new Date()));
        
        Movil.setVisible(true);
        inicio_sesion.setVisible(true);
        interfaz_alumno.setVisible(false);
        MenuAlumno.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Movil = new javax.swing.JPanel();
        Movil_imagen = new javax.swing.JLabel();
        Barra_notificaciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        inicio_sesion = new javax.swing.JPanel();
        Logo_UCO = new javax.swing.JLabel();
        Usuario_campo = new javax.swing.JTextField();
        Usuario_etiqueta = new javax.swing.JLabel();
        Contraseña_etiqueta = new javax.swing.JLabel();
        Contraseña_campo = new javax.swing.JPasswordField();
        Mostrar_contraseña = new javax.swing.JCheckBox();
        Password_olvidada = new javax.swing.JLabel();
        inicio_de_sesion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        Selecione_idioma1 = new javax.swing.JLabel();
        espanol_boton = new javax.swing.JButton();
        ingles_boton = new javax.swing.JButton();
        frances_boton = new javax.swing.JButton();
        interfaz_alumno = new javax.swing.JPanel();
        MenuAlumno = new javax.swing.JPanel();
        MenuBotonCerrar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Inicio_Imagen = new javax.swing.JLabel();
        Moodle = new javax.swing.JLabel();
        Moodle_imagen = new javax.swing.JLabel();
        Acerca_de = new javax.swing.JLabel();
        Acerca_de_imagen = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        MenuBoton = new javax.swing.JLabel();
        UCOApp = new javax.swing.JLabel();
        seleccion = new javax.swing.JPanel();
        Logo_UCO1 = new javax.swing.JLabel();
        consultar_notas_boton = new javax.swing.JButton();
        consultar_matricula_boton = new javax.swing.JButton();
        consultar_notas = new javax.swing.JPanel();
        Grado_Ingenieria = new javax.swing.JLabel();
        barra_creditos = new javax.swing.JProgressBar();
        creditos_etiqueta = new javax.swing.JLabel();
        escuela = new javax.swing.JLabel();
        primera_asignatura = new javax.swing.JPanel();
        titulo_primera = new javax.swing.JLabel();
        convocatoria_primero = new javax.swing.JLabel();
        aprobado_texto_primera = new javax.swing.JLabel();
        aprobado_fondo_primera = new javax.swing.JLabel();
        aprobado_nota_primera = new javax.swing.JLabel();
        aprobado_fondo_nota_primera = new javax.swing.JLabel();
        segunda_asignatura = new javax.swing.JPanel();
        titulo_segunda = new javax.swing.JLabel();
        convocatoria_segunda = new javax.swing.JLabel();
        aprobado_texto_segunda = new javax.swing.JLabel();
        aprobado_fondo_segunda = new javax.swing.JLabel();
        aprobado_nota_segunda = new javax.swing.JLabel();
        aprobado_fondo_nota_segunda = new javax.swing.JLabel();
        consultar_matricula = new javax.swing.JPanel();
        consultar_abonare_boton = new javax.swing.JButton();
        consultar_grupo_grande_boton = new javax.swing.JButton();
        consultar_grupo_practicas_boton = new javax.swing.JButton();
        consultar_abonare = new javax.swing.JPanel();
        PDF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("UCO App"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Movil.setBackground(new java.awt.Color(255, 255, 255));
        Movil.setName("Movil"); // NOI18N
        Movil.setOpaque(false);
        Movil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Movil_imagen.setBackground(new java.awt.Color(255, 255, 255));
        Movil_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cellphone.png"))); // NOI18N
        Movil_imagen.setName("Movil_imagen"); // NOI18N
        Movil.add(Movil_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 910));

        Barra_notificaciones.setBackground(new java.awt.Color(255, 255, 255));
        Barra_notificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Barra_notificaciones.setName("Barra_notificaciones"); // NOI18N
        Barra_notificaciones.setPreferredSize(new java.awt.Dimension(387, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signal-icon (1).jpg"))); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/battery-icon (1).jpg"))); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wireless-icon.svg (1).png"))); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        time.setName("time"); // NOI18N

        javax.swing.GroupLayout Barra_notificacionesLayout = new javax.swing.GroupLayout(Barra_notificaciones);
        Barra_notificaciones.setLayout(Barra_notificacionesLayout);
        Barra_notificacionesLayout.setHorizontalGroup(
            Barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_notificacionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Barra_notificacionesLayout.setVerticalGroup(
            Barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Barra_notificacionesLayout.createSequentialGroup()
                .addGroup(Barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Movil.add(Barra_notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 400, 32));

        getContentPane().add(Movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 910));

        inicio_sesion.setName("inicio_sesion"); // NOI18N

        Logo_UCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mobilephone2/bundle/Bundle"); // NOI18N
        Logo_UCO.setText(bundle.getString("Phone.Logo_UCO.text")); // NOI18N
        Logo_UCO.setName("Logo_UCO"); // NOI18N

        Usuario_campo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Usuario_campo.setText(bundle.getString("Phone.Usuario_campo.text")); // NOI18N
        Usuario_campo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        Usuario_campo.setName("Usuario_campo"); // NOI18N
        Usuario_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_campoActionPerformed(evt);
            }
        });

        Usuario_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Usuario_etiqueta.setText(bundle.getString("Phone.Usuario_etiqueta.text")); // NOI18N
        Usuario_etiqueta.setName("Usuario_etiqueta"); // NOI18N

        Contraseña_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Contraseña_etiqueta.setText(bundle.getString("Phone.Contraseña_etiqueta.text")); // NOI18N
        Contraseña_etiqueta.setName("Contraseña_etiqueta"); // NOI18N

        Contraseña_campo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Contraseña_campo.setText(bundle.getString("Phone.Contraseña_campo.text")); // NOI18N
        Contraseña_campo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        Contraseña_campo.setName("Contraseña_campo"); // NOI18N

        Mostrar_contraseña.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Mostrar_contraseña.setText(bundle.getString("Phone.Mostrar_contraseña.text")); // NOI18N
        Mostrar_contraseña.setName("Mostrar_contraseña"); // NOI18N
        Mostrar_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_contraseñaActionPerformed(evt);
            }
        });

        Password_olvidada.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        Password_olvidada.setText(bundle.getString("Phone.Password_olvidada.text")); // NOI18N
        Password_olvidada.setName("Password_olvidada"); // NOI18N

        inicio_de_sesion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        inicio_de_sesion.setText(bundle.getString("Phone.inicio_de_sesion.text")); // NOI18N
        inicio_de_sesion.setName("inicio_de_sesion"); // NOI18N
        inicio_de_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_de_sesionActionPerformed(evt);
            }
        });

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 125, 255)));
        jSeparator2.setName("jSeparator2"); // NOI18N

        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 125, 255)));
        jSeparator1.setName("jSeparator1"); // NOI18N

        Selecione_idioma1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Selecione_idioma1.setText(bundle.getString("Phone.Selecione_idioma1.text")); // NOI18N
        Selecione_idioma1.setName("Selecione_idioma1"); // NOI18N

        espanol_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera1_small.png"))); // NOI18N
        espanol_boton.setText(bundle.getString("Phone.espanol_boton.text")); // NOI18N
        espanol_boton.setName("espanol_boton"); // NOI18N
        espanol_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espanol_botonActionPerformed(evt);
            }
        });

        ingles_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera2.png"))); // NOI18N
        ingles_boton.setText(bundle.getString("Phone.ingles_boton.text")); // NOI18N
        ingles_boton.setName("ingles_boton"); // NOI18N
        ingles_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingles_botonActionPerformed(evt);
            }
        });

        frances_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera3.png"))); // NOI18N
        frances_boton.setText(bundle.getString("Phone.frances_boton.text")); // NOI18N
        frances_boton.setName("frances_boton"); // NOI18N
        frances_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frances_botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inicio_sesionLayout = new javax.swing.GroupLayout(inicio_sesion);
        inicio_sesion.setLayout(inicio_sesionLayout);
        inicio_sesionLayout.setHorizontalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_sesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_sesionLayout.createSequentialGroup()
                        .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Selecione_idioma1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Logo_UCO, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mostrar_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Password_olvidada)
                                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Usuario_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Usuario_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Contraseña_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Contraseña_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(103, 103, 103))))
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(espanol_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ingles_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(frances_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicio_sesionLayout.setVerticalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Logo_UCO)
                .addGap(27, 27, 27)
                .addComponent(Usuario_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Contraseña_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Password_olvidada, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mostrar_contraseña)
                .addGap(38, 38, 38)
                .addComponent(inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(Selecione_idioma1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espanol_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingles_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frances_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        getContentPane().add(inicio_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 64, 420, 820));
        inicio_sesion.setBackground(Color.WHITE);

        interfaz_alumno.setBackground(new java.awt.Color(255, 255, 255));
        interfaz_alumno.setName("interfaz_alumno"); // NOI18N
        interfaz_alumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuAlumno.setBackground(new java.awt.Color(255, 255, 255));
        MenuAlumno.setForeground(new java.awt.Color(43, 43, 43));
        MenuAlumno.setName("MenuAlumno"); // NOI18N

        MenuBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_111152.png"))); // NOI18N
        MenuBotonCerrar.setName("MenuBotonCerrar"); // NOI18N
        MenuBotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBotonCerrarMouseClicked(evt);
            }
        });

        Nombre.setText(bundle.getString("Phone.Nombre.text")); // NOI18N
        Nombre.setName("Nombre"); // NOI18N

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar.png"))); // NOI18N
        Imagen.setName("Imagen"); // NOI18N

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        Logout.setName("Logout"); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        Inicio.setText(bundle.getString("Phone.Inicio.text")); // NOI18N
        Inicio.setName("Inicio"); // NOI18N
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });

        Inicio_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        Inicio_Imagen.setName("Inicio_Imagen"); // NOI18N
        Inicio_Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inicio_ImagenMouseClicked(evt);
            }
        });

        Moodle.setText(bundle.getString("Phone.Moodle.text")); // NOI18N
        Moodle.setName("Moodle"); // NOI18N

        Moodle_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moodle.png"))); // NOI18N
        Moodle_imagen.setName("Moodle_imagen"); // NOI18N

        Acerca_de.setText(bundle.getString("Phone.Acerca_de.text")); // NOI18N
        Acerca_de.setName("Acerca_de"); // NOI18N

        Acerca_de_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        Acerca_de_imagen.setName("Acerca_de_imagen"); // NOI18N

        javax.swing.GroupLayout MenuAlumnoLayout = new javax.swing.GroupLayout(MenuAlumno);
        MenuAlumno.setLayout(MenuAlumnoLayout);
        MenuAlumnoLayout.setHorizontalGroup(
            MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuBotonCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Imagen)
                    .addComponent(Inicio_Imagen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Acerca_de_imagen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Moodle_imagen, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Acerca_de)
                    .addComponent(Moodle)
                    .addComponent(Inicio))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        MenuAlumnoLayout.setVerticalGroup(
            MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuBotonCerrar)
                .addGap(18, 18, 18)
                .addComponent(Logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(Inicio))
                    .addComponent(Inicio_Imagen))
                .addGap(26, 26, 26)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addComponent(Moodle)
                        .addGap(30, 30, 30)
                        .addComponent(Acerca_de))
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addComponent(Moodle_imagen)
                        .addGap(18, 18, 18)
                        .addComponent(Acerca_de_imagen)))
                .addGap(517, 517, 517))
        );

        interfaz_alumno.add(MenuAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 780));

        Header.setBackground(new java.awt.Color(53, 53, 255));
        Header.setName("Header"); // NOI18N

        MenuBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-button.png"))); // NOI18N
        MenuBoton.setName("MenuBoton"); // NOI18N
        MenuBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBotonMouseClicked(evt);
            }
        });

        UCOApp.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        UCOApp.setText(bundle.getString("Phone.UCOApp.text")); // NOI18N
        UCOApp.setName("UCOApp"); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(MenuBoton)
                .addGap(18, 18, 18)
                .addComponent(UCOApp)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(MenuBoton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(UCOApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        interfaz_alumno.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 60));

        seleccion.setName("seleccion"); // NOI18N

        Logo_UCO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        Logo_UCO1.setText(bundle.getString("Phone.Logo_UCO1.text")); // NOI18N
        Logo_UCO1.setName("Logo_UCO1"); // NOI18N

        consultar_notas_boton.setBackground(new java.awt.Color(79, 79, 253));
        consultar_notas_boton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        consultar_notas_boton.setText(bundle.getString("Phone.consultar_notas_boton.text")); // NOI18N
        consultar_notas_boton.setName("consultar_notas_boton"); // NOI18N
        consultar_notas_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_notas_botonActionPerformed(evt);
            }
        });

        consultar_matricula_boton.setBackground(new java.awt.Color(53, 255, 53));
        consultar_matricula_boton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        consultar_matricula_boton.setText(bundle.getString("Phone.consultar_matricula_boton.text")); // NOI18N
        consultar_matricula_boton.setName("consultar_matricula_boton"); // NOI18N
        consultar_matricula_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_matricula_botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccionLayout = new javax.swing.GroupLayout(seleccion);
        seleccion.setLayout(seleccionLayout);
        seleccionLayout.setHorizontalGroup(
            seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionLayout.createSequentialGroup()
                .addGroup(seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seleccionLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Logo_UCO1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seleccionLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(consultar_notas_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(consultar_matricula_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        seleccionLayout.setVerticalGroup(
            seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Logo_UCO1)
                .addGap(187, 187, 187)
                .addGroup(seleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar_notas_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar_matricula_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        interfaz_alumno.add(seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 720));

        consultar_notas.setBackground(new java.awt.Color(255, 255, 255));
        consultar_notas.setName("consultar_notas"); // NOI18N
        consultar_notas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Grado_Ingenieria.setFont(new java.awt.Font("Ubuntu", 1, 23)); // NOI18N
        Grado_Ingenieria.setForeground(new java.awt.Color(0, 0, 0));
        Grado_Ingenieria.setText(bundle.getString("Phone.Grado_Ingenieria.text")); // NOI18N
        Grado_Ingenieria.setName("Grado_Ingenieria"); // NOI18N
        consultar_notas.add(Grado_Ingenieria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        barra_creditos.setMaximum(240);
        barra_creditos.setValue(60);
        barra_creditos.setName("barra_creditos"); // NOI18N
        consultar_notas.add(barra_creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 10));

        creditos_etiqueta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        creditos_etiqueta.setForeground(new java.awt.Color(0, 0, 0));
        creditos_etiqueta.setText(bundle.getString("Phone.creditos_etiqueta.text")); // NOI18N
        creditos_etiqueta.setName("creditos_etiqueta"); // NOI18N
        consultar_notas.add(creditos_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        escuela.setForeground(new java.awt.Color(0, 0, 0));
        escuela.setText(bundle.getString("Phone.escuela.text")); // NOI18N
        escuela.setName("escuela"); // NOI18N
        consultar_notas.add(escuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        primera_asignatura.setName("primera_asignatura"); // NOI18N
        primera_asignatura.setOpaque(false);
        primera_asignatura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_primera.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_primera.setForeground(new java.awt.Color(0, 0, 0));
        titulo_primera.setText(bundle.getString("Phone.titulo_primera.text")); // NOI18N
        titulo_primera.setName("titulo_primera"); // NOI18N
        primera_asignatura.add(titulo_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 12, -1, -1));

        convocatoria_primero.setForeground(new java.awt.Color(0, 0, 0));
        convocatoria_primero.setText(bundle.getString("Phone.convocatoria_primero.text")); // NOI18N
        convocatoria_primero.setName("convocatoria_primero"); // NOI18N
        primera_asignatura.add(convocatoria_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 39, -1, -1));

        aprobado_texto_primera.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_texto_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_texto_primera.setText(bundle.getString("Phone.aprobado_texto_primera.text")); // NOI18N
        aprobado_texto_primera.setName("aprobado_texto_primera"); // NOI18N
        primera_asignatura.add(aprobado_texto_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        aprobado_fondo_primera.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_primera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_primera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yellow_circle.png"))); // NOI18N
        aprobado_fondo_primera.setText(bundle.getString("Phone.aprobado_fondo_primera.text")); // NOI18N
        aprobado_fondo_primera.setName("aprobado_fondo_primera"); // NOI18N
        primera_asignatura.add(aprobado_fondo_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        aprobado_nota_primera.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_nota_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_nota_primera.setText(bundle.getString("Phone.aprobado_nota_primera.text")); // NOI18N
        aprobado_nota_primera.setName("aprobado_nota_primera"); // NOI18N
        primera_asignatura.add(aprobado_nota_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 40));

        aprobado_fondo_nota_primera.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_nota_primera.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_nota_primera.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_nota_primera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yellow_circle.png"))); // NOI18N
        aprobado_fondo_nota_primera.setText(bundle.getString("Phone.aprobado_fondo_nota_primera.text")); // NOI18N
        aprobado_fondo_nota_primera.setName("aprobado_fondo_nota_primera"); // NOI18N
        primera_asignatura.add(aprobado_fondo_nota_primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_notas.add(primera_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 80));

        segunda_asignatura.setName("segunda_asignatura"); // NOI18N
        segunda_asignatura.setOpaque(false);
        segunda_asignatura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_segunda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo_segunda.setForeground(new java.awt.Color(0, 0, 0));
        titulo_segunda.setText(bundle.getString("Phone.titulo_segunda.text")); // NOI18N
        titulo_segunda.setName("titulo_segunda"); // NOI18N
        segunda_asignatura.add(titulo_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 12, -1, -1));

        convocatoria_segunda.setForeground(new java.awt.Color(0, 0, 0));
        convocatoria_segunda.setText(bundle.getString("Phone.convocatoria_segunda.text")); // NOI18N
        convocatoria_segunda.setName("convocatoria_segunda"); // NOI18N
        segunda_asignatura.add(convocatoria_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 39, -1, -1));

        aprobado_texto_segunda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_texto_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_texto_segunda.setText(bundle.getString("Phone.aprobado_texto_segunda.text")); // NOI18N
        aprobado_texto_segunda.setName("aprobado_texto_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_texto_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        aprobado_fondo_segunda.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_segunda.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_segunda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_circle.png"))); // NOI18N
        aprobado_fondo_segunda.setText(bundle.getString("Phone.aprobado_fondo_segunda.text")); // NOI18N
        aprobado_fondo_segunda.setName("aprobado_fondo_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_fondo_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 45));

        aprobado_nota_segunda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aprobado_nota_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_nota_segunda.setText(bundle.getString("Phone.aprobado_nota_segunda.text")); // NOI18N
        aprobado_nota_segunda.setName("aprobado_nota_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_nota_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 40));

        aprobado_fondo_nota_segunda.setBackground(new java.awt.Color(255, 255, 0));
        aprobado_fondo_nota_segunda.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        aprobado_fondo_nota_segunda.setForeground(new java.awt.Color(0, 0, 0));
        aprobado_fondo_nota_segunda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_circle.png"))); // NOI18N
        aprobado_fondo_nota_segunda.setText(bundle.getString("Phone.aprobado_fondo_nota_segunda.text")); // NOI18N
        aprobado_fondo_nota_segunda.setName("aprobado_fondo_nota_segunda"); // NOI18N
        segunda_asignatura.add(aprobado_fondo_nota_segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, 45));

        consultar_notas.add(segunda_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 430, 80));

        interfaz_alumno.add(consultar_notas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        consultar_matricula.setBackground(new java.awt.Color(255, 255, 255));
        consultar_matricula.setName("consultar_matricula"); // NOI18N
        consultar_matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultar_abonare_boton.setText(bundle.getString("Phone.consultar_abonare_boton.text")); // NOI18N
        consultar_abonare_boton.setName("consultar_abonare_boton"); // NOI18N
        consultar_abonare_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_abonare_botonActionPerformed(evt);
            }
        });
        consultar_matricula.add(consultar_abonare_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 70));

        consultar_grupo_grande_boton.setText(bundle.getString("Phone.consultar_grupo_grande_boton.text")); // NOI18N
        consultar_grupo_grande_boton.setName("consultar_grupo_grande_boton"); // NOI18N
        consultar_grupo_grande_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_grupo_grande_botonActionPerformed(evt);
            }
        });
        consultar_matricula.add(consultar_grupo_grande_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 400, 70));

        consultar_grupo_practicas_boton.setText(bundle.getString("Phone.consultar_grupo_practicas_boton.text")); // NOI18N
        consultar_grupo_practicas_boton.setName("consultar_grupo_practicas_boton"); // NOI18N
        consultar_grupo_practicas_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_grupo_practicas_botonActionPerformed(evt);
            }
        });
        consultar_matricula.add(consultar_grupo_practicas_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 400, 70));

        interfaz_alumno.add(consultar_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        consultar_abonare.setBackground(new java.awt.Color(255, 255, 255));
        consultar_abonare.setName("consultar_abonare"); // NOI18N
        consultar_abonare.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PDF.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        PDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PDF.setText(bundle.getString("Phone.PDF.text")); // NOI18N
        PDF.setName("PDF"); // NOI18N
        PDF.setOpaque(true);
        consultar_abonare.add(PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 780));

        interfaz_alumno.add(consultar_abonare, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 400, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        getContentPane().add(interfaz_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 64, 390, 780));
        interfaz_alumno.setBackground(Color.WHITE);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicio_de_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_de_sesionActionPerformed
        // TODO add your handling code here:
        inicio_sesion.setVisible(false);
        interfaz_alumno.setVisible(true);
            seleccion.setVisible(true);
            consultar_matricula.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_inicio_de_sesionActionPerformed

    private void Mostrar_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_contraseñaActionPerformed
        // TODO add your handling code here:
        if(Mostrar_contraseña.isSelected())
        Contraseña_campo.setEchoChar((char)0);
        else
        Contraseña_campo.setEchoChar('*');
    }//GEN-LAST:event_Mostrar_contraseñaActionPerformed

    private void Usuario_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_campoActionPerformed

    private void MenuBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBotonMouseClicked
        MenuAlumno.setVisible(true);
    }//GEN-LAST:event_MenuBotonMouseClicked

    private void MenuBotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBotonCerrarMouseClicked
        MenuAlumno.setVisible(false);
    }//GEN-LAST:event_MenuBotonCerrarMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        MenuAlumno.setVisible(false);
        interfaz_alumno.setVisible(false);
        inicio_sesion.setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void Inicio_ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inicio_ImagenMouseClicked
        MenuAlumno.setVisible(false);
        seleccion.setVisible(true);
    }//GEN-LAST:event_Inicio_ImagenMouseClicked

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        MenuAlumno.setVisible(false);
        seleccion.setVisible(true);
    }//GEN-LAST:event_InicioMouseClicked

    private void consultar_notas_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_notas_botonActionPerformed
        // TODO add your handling code here:
        seleccion.setVisible(false);
        consultar_notas.setVisible(true);

        pack();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_consultar_notas_botonActionPerformed

    private void espanol_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espanol_botonActionPerformed
        // TODO add your handling code here:
        currentLocale = new Locale("es", "ES");
        
        ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
    }//GEN-LAST:event_espanol_botonActionPerformed

    private void ingles_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingles_botonActionPerformed
        // TODO add your handling code here:
        currentLocale = new Locale("en", "GB");
        
        ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
    }//GEN-LAST:event_ingles_botonActionPerformed

    private void frances_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frances_botonActionPerformed
        // TODO add your handling code here:
        currentLocale = new Locale("fr", "FR");

        ResourceBundle.getBundle("mobilephone2.bundle.Bundle", currentLocale);
    }//GEN-LAST:event_frances_botonActionPerformed

    private void consultar_matricula_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_matricula_botonActionPerformed
        // TODO add your handling code here:
        seleccion.setVisible(false);
        consultar_matricula.setVisible(true);
    }//GEN-LAST:event_consultar_matricula_botonActionPerformed

    private void consultar_abonare_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_abonare_botonActionPerformed
        // TODO add your handling code here:
        consultar_matricula.setVisible(false);
        consultar_abonare.setVisible(true);
    }//GEN-LAST:event_consultar_abonare_botonActionPerformed

    private void consultar_grupo_grande_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_grupo_grande_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultar_grupo_grande_botonActionPerformed

    private void consultar_grupo_practicas_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_grupo_practicas_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultar_grupo_practicas_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acerca_de;
    private javax.swing.JLabel Acerca_de_imagen;
    private javax.swing.JPanel Barra_notificaciones;
    private javax.swing.JPasswordField Contraseña_campo;
    private javax.swing.JLabel Contraseña_etiqueta;
    private javax.swing.JLabel Grado_Ingenieria;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Inicio_Imagen;
    private javax.swing.JLabel Logo_UCO;
    private javax.swing.JLabel Logo_UCO1;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel MenuAlumno;
    private javax.swing.JLabel MenuBoton;
    private javax.swing.JLabel MenuBotonCerrar;
    private javax.swing.JLabel Moodle;
    private javax.swing.JLabel Moodle_imagen;
    private javax.swing.JCheckBox Mostrar_contraseña;
    private javax.swing.JPanel Movil;
    private javax.swing.JLabel Movil_imagen;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PDF;
    private javax.swing.JLabel Password_olvidada;
    private javax.swing.JLabel Selecione_idioma1;
    private javax.swing.JLabel UCOApp;
    private javax.swing.JTextField Usuario_campo;
    private javax.swing.JLabel Usuario_etiqueta;
    private javax.swing.JLabel aprobado_fondo_nota_primera;
    private javax.swing.JLabel aprobado_fondo_nota_segunda;
    private javax.swing.JLabel aprobado_fondo_primera;
    private javax.swing.JLabel aprobado_fondo_segunda;
    private javax.swing.JLabel aprobado_nota_primera;
    private javax.swing.JLabel aprobado_nota_segunda;
    private javax.swing.JLabel aprobado_texto_primera;
    private javax.swing.JLabel aprobado_texto_segunda;
    private javax.swing.JProgressBar barra_creditos;
    private javax.swing.JPanel consultar_abonare;
    private javax.swing.JButton consultar_abonare_boton;
    private javax.swing.JButton consultar_grupo_grande_boton;
    private javax.swing.JButton consultar_grupo_practicas_boton;
    private javax.swing.JPanel consultar_matricula;
    private javax.swing.JButton consultar_matricula_boton;
    private javax.swing.JPanel consultar_notas;
    private javax.swing.JButton consultar_notas_boton;
    private javax.swing.JLabel convocatoria_primero;
    private javax.swing.JLabel convocatoria_segunda;
    private javax.swing.JLabel creditos_etiqueta;
    private javax.swing.JLabel escuela;
    private javax.swing.JButton espanol_boton;
    private javax.swing.JButton frances_boton;
    private javax.swing.JButton ingles_boton;
    private javax.swing.JButton inicio_de_sesion;
    private javax.swing.JPanel inicio_sesion;
    private javax.swing.JPanel interfaz_alumno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel primera_asignatura;
    private javax.swing.JPanel segunda_asignatura;
    private javax.swing.JPanel seleccion;
    private javax.swing.JLabel time;
    private javax.swing.JLabel titulo_primera;
    private javax.swing.JLabel titulo_segunda;
    // End of variables declaration//GEN-END:variables
}
