/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucoapp;

/**
 *
 * @author fran
 */
public class Phone extends javax.swing.JFrame {

    /**
     * Creates new form Phone
     */
    public Phone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Inicio_sesion = new javax.swing.JPanel();
        Logo_UCO = new javax.swing.JLabel();
        Bandera1 = new javax.swing.JLabel();
        Bandera2 = new javax.swing.JLabel();
        Bandera3 = new javax.swing.JLabel();
        Usuario_campo = new javax.swing.JTextField();
        Usuario_etiqueta = new javax.swing.JLabel();
        Contraseña_etiqueta = new javax.swing.JLabel();
        Contraseña_campo = new javax.swing.JPasswordField();
        Mostrar_contraseña = new javax.swing.JCheckBox();
        Password_olvidada = new javax.swing.JLabel();
        Profesor_boton = new javax.swing.JButton();
        Alumno_boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setOpaque(false);
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smartphone_little.png"))); // NOI18N
        body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 525, 1017));

        Inicio_sesion.setBackground(new java.awt.Color(255, 255, 255));

        Logo_UCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        Logo_UCO.setText("jLabel2");

        Bandera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera1_small.png"))); // NOI18N
        Bandera1.setText("jLabel2");

        Bandera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera2.png"))); // NOI18N
        Bandera2.setText("jLabel2");

        Bandera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera3.png"))); // NOI18N
        Bandera3.setText("jLabel2");

        Usuario_campo.setBackground(new java.awt.Color(255, 255, 255));
        Usuario_campo.setText("Usuario1");
        Usuario_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_campoActionPerformed(evt);
            }
        });

        Usuario_etiqueta.setForeground(new java.awt.Color(0, 0, 0));
        Usuario_etiqueta.setText("Usuario");

        Contraseña_etiqueta.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña_etiqueta.setText("Contraseña");

        Contraseña_campo.setText("Contraseña1");

        Mostrar_contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Mostrar_contraseña.setText("Mostrar contraseña");
        Mostrar_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_contraseñaActionPerformed(evt);
            }
        });

        Password_olvidada.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        Password_olvidada.setForeground(new java.awt.Color(0, 0, 0));
        Password_olvidada.setText("Contraseña olvidada");

        Profesor_boton.setText("Profesor");

        Alumno_boton.setText("Alumno");

        javax.swing.GroupLayout Inicio_sesionLayout = new javax.swing.GroupLayout(Inicio_sesion);
        Inicio_sesion.setLayout(Inicio_sesionLayout);
        Inicio_sesionLayout.setHorizontalGroup(
            Inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inicio_sesionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Bandera1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bandera2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Bandera3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(Inicio_sesionLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(Inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Inicio_sesionLayout.createSequentialGroup()
                        .addGroup(Inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password_olvidada)
                            .addGroup(Inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Logo_UCO, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Usuario_campo)
                                .addComponent(Usuario_etiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Contraseña_etiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Contraseña_campo)
                                .addComponent(Mostrar_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Inicio_sesionLayout.createSequentialGroup()
                        .addComponent(Profesor_boton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Alumno_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );
        Inicio_sesionLayout.setVerticalGroup(
            Inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicio_sesionLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Logo_UCO)
                .addGap(45, 45, 45)
                .addComponent(Usuario_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Contraseña_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_olvidada, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Mostrar_contraseña)
                .addGap(47, 47, 47)
                .addGroup(Inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Alumno_boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profesor_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(Inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bandera3)
                    .addComponent(Bandera1)
                    .addComponent(Bandera2))
                .addGap(71, 71, 71))
        );

        body.add(Inicio_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 460, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Usuario_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_campoActionPerformed

    private void Mostrar_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mostrar_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alumno_boton;
    private javax.swing.JLabel Bandera1;
    private javax.swing.JLabel Bandera2;
    private javax.swing.JLabel Bandera3;
    private javax.swing.JPasswordField Contraseña_campo;
    private javax.swing.JLabel Contraseña_etiqueta;
    private javax.swing.JPanel Inicio_sesion;
    private javax.swing.JLabel Logo_UCO;
    private javax.swing.JCheckBox Mostrar_contraseña;
    private javax.swing.JLabel Password_olvidada;
    private javax.swing.JButton Profesor_boton;
    private javax.swing.JTextField Usuario_campo;
    private javax.swing.JLabel Usuario_etiqueta;
    private javax.swing.JPanel body;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
