/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mobilephone2;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Manuel Izquierdo
 * @author Francisco Llamas
 */
public class Phone extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
    
    public Phone() {
        //setUndecorated(true);
        initComponents();
        //setBackground(new Color(0,0,0,0));
        //body.setBackground(Color.WHITE);
        time.setText(sdf.format(new Date()));
        
        Movil.setVisible(true);
        inicio_sesion.setVisible(true);
        interfaz_alumno.setVisible(false);
        MenuAlumno.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Movil = new javax.swing.JPanel();
        Movil_imagen = new javax.swing.JLabel();
        Barra_notificaciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        inicio_sesion = new javax.swing.JPanel();
        Logo_UCO = new javax.swing.JLabel();
        Bandera1 = new javax.swing.JLabel();
        Bandera2 = new javax.swing.JLabel();
        Bandera3 = new javax.swing.JLabel();
        Usuario_campo = new javax.swing.JTextField();
        Usuario_etiqueta = new javax.swing.JLabel();
        Contraseña_etiqueta = new javax.swing.JLabel();
        Contraseña_campo = new javax.swing.JPasswordField();
        Mostrar_contraseña = new javax.swing.JCheckBox();
        Password_olvidada = new javax.swing.JLabel();
        inicio_de_sesion = new javax.swing.JButton();
        Selecione_idioma = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        interfaz_alumno = new javax.swing.JPanel();
        MenuAlumno = new javax.swing.JPanel();
        MenuBotonCerrar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Inicio_Imagen = new javax.swing.JLabel();
        Moodle = new javax.swing.JLabel();
        Moodle_imagen = new javax.swing.JLabel();
        Acerca_de = new javax.swing.JLabel();
        Acerca_de_imagen = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        MenuBoton = new javax.swing.JLabel();
        UCOApp = new javax.swing.JLabel();
        Logo_UCO1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("UCO App"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Movil.setBackground(new java.awt.Color(255, 255, 255));
        Movil.setOpaque(false);
        Movil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Movil_imagen.setBackground(new java.awt.Color(255, 255, 255));
        Movil_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cellphone.png"))); // NOI18N
        Movil.add(Movil_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 910));

        Barra_notificaciones.setBackground(new java.awt.Color(255, 255, 255));
        Barra_notificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Barra_notificaciones.setPreferredSize(new java.awt.Dimension(387, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signal-icon (1).jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/battery-icon (1).jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wireless-icon.svg (1).png"))); // NOI18N

        time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout Barra_notificacionesLayout = new javax.swing.GroupLayout(Barra_notificaciones);
        Barra_notificaciones.setLayout(Barra_notificacionesLayout);
        Barra_notificacionesLayout.setHorizontalGroup(
            Barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_notificacionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Barra_notificacionesLayout.setVerticalGroup(
            Barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Barra_notificacionesLayout.createSequentialGroup()
                .addGroup(Barra_notificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Movil.add(Barra_notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 400, 32));

        getContentPane().add(Movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 910));

        Logo_UCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        Logo_UCO.setText("jLabel2");

        Bandera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera1_small.png"))); // NOI18N
        Bandera1.setText("jLabel2");

        Bandera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera2.png"))); // NOI18N
        Bandera2.setText("jLabel2");

        Bandera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera3.png"))); // NOI18N
        Bandera3.setText("jLabel2");

        Usuario_campo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Usuario_campo.setText("Usuario1");
        Usuario_campo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));
        Usuario_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_campoActionPerformed(evt);
            }
        });

        Usuario_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Usuario_etiqueta.setText("Usuario");

        Contraseña_etiqueta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Contraseña_etiqueta.setText("Contraseña");

        Contraseña_campo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Contraseña_campo.setText("Contraseña1");
        Contraseña_campo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 255)));

        Mostrar_contraseña.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Mostrar_contraseña.setText("Mostrar contraseña");
        Mostrar_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_contraseñaActionPerformed(evt);
            }
        });

        Password_olvidada.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        Password_olvidada.setText("Contraseña olvidada");

        inicio_de_sesion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        inicio_de_sesion.setText("Iniciar Sesión");
        inicio_de_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_de_sesionActionPerformed(evt);
            }
        });

        Selecione_idioma.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Selecione_idioma.setText("                 Selección de idioma:");

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 125, 255)));

        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 125, 255)));

        javax.swing.GroupLayout inicio_sesionLayout = new javax.swing.GroupLayout(inicio_sesion);
        inicio_sesion.setLayout(inicio_sesionLayout);
        inicio_sesionLayout.setHorizontalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Bandera1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bandera2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bandera3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Selecione_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_sesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_sesionLayout.createSequentialGroup()
                        .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logo_UCO, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mostrar_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_olvidada)
                            .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Usuario_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Usuario_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Contraseña_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Contraseña_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        inicio_sesionLayout.setVerticalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Logo_UCO)
                .addGap(27, 27, 27)
                .addComponent(Usuario_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Contraseña_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Password_olvidada, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mostrar_contraseña)
                .addGap(38, 38, 38)
                .addComponent(inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Selecione_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bandera2)
                    .addComponent(Bandera1)
                    .addComponent(Bandera3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        getContentPane().add(inicio_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 64, 420, 820));
        inicio_sesion.setBackground(Color.WHITE);

        interfaz_alumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuAlumno.setBackground(new java.awt.Color(255, 255, 255));
        MenuAlumno.setForeground(new java.awt.Color(43, 43, 43));

        MenuBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_111152.png"))); // NOI18N
        MenuBotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBotonCerrarMouseClicked(evt);
            }
        });

        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Alumno1");

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar.png"))); // NOI18N

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        Inicio.setForeground(new java.awt.Color(0, 0, 0));
        Inicio.setText("Inicio");
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });

        Inicio_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        Inicio_Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inicio_ImagenMouseClicked(evt);
            }
        });

        Moodle.setForeground(new java.awt.Color(0, 0, 0));
        Moodle.setText("Moodle");

        Moodle_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moodle.png"))); // NOI18N

        Acerca_de.setForeground(new java.awt.Color(0, 0, 0));
        Acerca_de.setText("Acerca de");

        Acerca_de_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N

        javax.swing.GroupLayout MenuAlumnoLayout = new javax.swing.GroupLayout(MenuAlumno);
        MenuAlumno.setLayout(MenuAlumnoLayout);
        MenuAlumnoLayout.setHorizontalGroup(
            MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuBotonCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Imagen)
                    .addComponent(Inicio_Imagen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Acerca_de_imagen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Moodle_imagen, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Acerca_de)
                            .addComponent(Moodle)
                            .addComponent(Inicio))
                        .addGap(82, 82, 82)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        MenuAlumnoLayout.setVerticalGroup(
            MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuBotonCerrar)
                .addGap(18, 18, 18)
                .addComponent(Logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(Inicio))
                    .addComponent(Inicio_Imagen))
                .addGap(26, 26, 26)
                .addGroup(MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addComponent(Moodle)
                        .addGap(30, 30, 30)
                        .addComponent(Acerca_de))
                    .addGroup(MenuAlumnoLayout.createSequentialGroup()
                        .addComponent(Moodle_imagen)
                        .addGap(18, 18, 18)
                        .addComponent(Acerca_de_imagen)))
                .addGap(517, 517, 517))
        );

        interfaz_alumno.add(MenuAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 780));

        Header.setBackground(new java.awt.Color(53, 53, 255));

        MenuBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-button.png"))); // NOI18N
        MenuBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBotonMouseClicked(evt);
            }
        });

        UCOApp.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        UCOApp.setText("UCO App");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(MenuBoton)
                .addGap(18, 18, 18)
                .addComponent(UCOApp)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(MenuBoton)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(UCOApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        interfaz_alumno.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        Logo_UCO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_uco_small.png"))); // NOI18N
        Logo_UCO1.setText("jLabel2");
        interfaz_alumno.add(Logo_UCO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 106, 201, -1));

        jButton1.setBackground(new java.awt.Color(53, 255, 53));
        jButton1.setText("Consultar notas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        interfaz_alumno.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 130, 110));

        getContentPane().add(interfaz_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 64, 420, 820));
        interfaz_alumno.setBackground(Color.WHITE);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicio_de_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_de_sesionActionPerformed
        // TODO add your handling code here:
        inicio_sesion.setVisible(false);
        interfaz_alumno.setVisible(true);

        pack();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_inicio_de_sesionActionPerformed

    private void Mostrar_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_contraseñaActionPerformed
        // TODO add your handling code here:
        if(Mostrar_contraseña.isSelected())
        Contraseña_campo.setEchoChar((char)0);
        else
        Contraseña_campo.setEchoChar('*');
    }//GEN-LAST:event_Mostrar_contraseñaActionPerformed

    private void Usuario_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_campoActionPerformed

    private void MenuBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBotonMouseClicked
        MenuAlumno.setVisible(true);
    }//GEN-LAST:event_MenuBotonMouseClicked

    private void MenuBotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBotonCerrarMouseClicked
        MenuAlumno.setVisible(false);
    }//GEN-LAST:event_MenuBotonCerrarMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        MenuAlumno.setVisible(false);
        interfaz_alumno.setVisible(false);
        inicio_sesion.setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void Inicio_ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inicio_ImagenMouseClicked
        MenuAlumno.setVisible(false);
    }//GEN-LAST:event_Inicio_ImagenMouseClicked

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        MenuAlumno.setVisible(false);
    }//GEN-LAST:event_InicioMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acerca_de;
    private javax.swing.JLabel Acerca_de_imagen;
    private javax.swing.JLabel Bandera1;
    private javax.swing.JLabel Bandera2;
    private javax.swing.JLabel Bandera3;
    private javax.swing.JPanel Barra_notificaciones;
    private javax.swing.JPasswordField Contraseña_campo;
    private javax.swing.JLabel Contraseña_etiqueta;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Inicio_Imagen;
    private javax.swing.JLabel Logo_UCO;
    private javax.swing.JLabel Logo_UCO1;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel MenuAlumno;
    private javax.swing.JLabel MenuBoton;
    private javax.swing.JLabel MenuBotonCerrar;
    private javax.swing.JLabel Moodle;
    private javax.swing.JLabel Moodle_imagen;
    private javax.swing.JCheckBox Mostrar_contraseña;
    private javax.swing.JPanel Movil;
    private javax.swing.JLabel Movil_imagen;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Password_olvidada;
    private javax.swing.JLabel Selecione_idioma;
    private javax.swing.JLabel UCOApp;
    private javax.swing.JTextField Usuario_campo;
    private javax.swing.JLabel Usuario_etiqueta;
    private javax.swing.JButton inicio_de_sesion;
    private javax.swing.JPanel inicio_sesion;
    private javax.swing.JPanel interfaz_alumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
